
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: processor
  namespace: argocd
spec:
  project: workflow-project
  source:
    repoURL: https://github.com/vishnupillai704/argocd-deployment.git
    targetRevision: main
    path: .
    directory:
      recurse: true
      include: processor/*
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    